#!/bin/bash

CURRENT_DIR=$(dirname $(readlink -f $0))


DOCKER_REGISTRY="repo.acip.io"
COMMAND=$1

if [ "$#" -lt 1 ]; then
  echo "
  Usage: manage-docker [COMMAND] [PARAMETERS]

  A script that handles docker image process

  Commands:

    login [username password]: logs you in to $DOCKER_REGISTRY
    images                   : lists locally available images
    push  [image_label]      : pushes image_label to $DOCKER_REGISTRY
    pull  [image_label]      : pulls and saves image_label from $DOCKER_REGISTRY

  Parameters:

    username                 : username for repo
    password                 : user password for repo
    image_label              : name of the image (format: $DOCKER_REGISTRY/image_name)
"

else

  wget -q --spider http://google.com

  if [ $? -eq 0 ]; then
    if [ $1 = "login" ]; then
      USERNAME=$2
      PASSWORD=$3
      docker login -u $USERNAME -p $PASSWORD $DOCKER_REGISTRY
    fi

    if [ $1 = "push" ]; then
      IMAGE_LABEL=$2
      docker push $IMAGE_LABEL
    fi

    if [ $1 = "pull" ]; then
      IMAGE_LABEL=$2
      readarray -d / -t arr <<< $IMAGE_LABEL
      docker pull $IMAGE_LABEL
      docker save $IMAGE_LABEL | gzip -c > image.tar.gz
    fi
  fi


  if [ $1 = "images" ]; then
    IMAGE_LABEL=$2
    docker images
  fi

  if [ $1 = "load" ]; then
    IMAGE_LABEL=$2
    docker load -i $2
  fi
fi
